import { useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Building2, TrendingUp, FileText, ChevronDown, ChevronUp } from 'lucide-react';

// ── Skeleton shown while AI is analyzing in the modal ────────────────
export function AISummarySkeleton() {
  return (
    <div
      className="my-4 rounded-[10px]"
      style={{
        background: '#EEF2FE',
        borderLeft: '3px solid #4F39F5',
        border: '1px solid #E0E7FF',
        borderLeftWidth: '3px',
        borderLeftColor: '#4F39F5',
        padding: '12px 16px',
      }}
    >
      <div className="flex items-center justify-between mb-3">
        <div className="ai-shimmer" style={{ width: 120, height: 10 }} />
        <div className="ai-shimmer" style={{ width: 80, height: 18, borderRadius: 9999 }} />
      </div>
      <div className="ai-shimmer mb-2" style={{ width: '40%', height: 12 }} />
      <div style={{ height: 1, background: '#E0E7FF', margin: '8px 0' }} />
      <div className="ai-shimmer mb-2" style={{ width: '30%', height: 12 }} />
      <div style={{ height: 1, background: '#E0E7FF', margin: '8px 0' }} />
      <div className="ai-shimmer mb-1" style={{ width: '100%', height: 10 }} />
      <div className="ai-shimmer" style={{ width: '75%', height: 10 }} />
      <p
        className="mt-2"
        style={{
          fontFamily: 'Manrope, sans-serif',
          fontWeight: 500,
          fontSize: '11px',
          color: '#4F39F5',
        }}
      >
        Analyzing document...
      </p>
    </div>
  );
}

// ── Main Summary Card ────────────────────────────────────────────────
export function AISummaryCard({ summary }) {
  const [collapsed, setCollapsed] = useState(false);

  if (!summary) return null;

  const { startup_name, funding_amount, summary: summaryText } = summary;

  // Don't render if AI couldn't extract anything useful
  if (startup_name === 'Unknown' && funding_amount === 'Not disclosed' && summaryText?.includes('does not appear')) {
    return null;
  }

  return (
    <motion.div
      role="region"
      aria-label="AI-generated pitch deck summary"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, ease: 'easeOut', delay: 0.1 }}
      className="my-4 rounded-[10px] transition-shadow hover:shadow-md"
      style={{
        background: 'linear-gradient(135deg, #EEF2FE 0%, #F5F3FF 100%)',
        border: '1px solid #E0E7FF',
        borderLeftWidth: '3px',
        borderLeftColor: '#4F39F5',
        padding: '12px 16px',
      }}
    >
      {/* Header row */}
      <div className="flex items-center justify-between mb-2">
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="flex items-center gap-1.5 bg-transparent border-none cursor-pointer p-0"
          aria-label={collapsed ? 'Expand AI summary' : 'Collapse AI summary'}
        >
          <span
            style={{
              fontFamily: 'Manrope, sans-serif',
              fontWeight: 600,
              fontSize: '10px',
              textTransform: 'uppercase',
              color: '#62748E',
              letterSpacing: '0.5px',
            }}
          >
            PITCH DECK INSIGHTS
          </span>
          {collapsed
            ? <ChevronDown size={12} color="#62748E" />
            : <ChevronUp size={12} color="#62748E" />
          }
        </button>

        <span
          aria-label="This summary was generated by AI"
          className="inline-flex items-center gap-1 select-none"
          style={{
            background: 'linear-gradient(135deg, #4F39F5, #6366F1)',
            color: '#FFFFFF',
            fontFamily: 'Manrope, sans-serif',
            fontWeight: 600,
            fontSize: '10px',
            textTransform: 'uppercase',
            padding: '3px 8px',
            borderRadius: '9999px',
            letterSpacing: '0.3px',
          }}
        >
          <Sparkles size={10} />
          AI Summary
        </span>
      </div>

      {!collapsed && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: 'auto' }}
          exit={{ opacity: 0, height: 0 }}
          transition={{ duration: 0.2 }}
        >
          {/* Row 1 — Company */}
          <div className="flex items-center py-2" style={{ gap: '8px' }}>
            <div className="flex items-center gap-1.5" style={{ minWidth: '80px' }}>
              <Building2 size={12} color="#62748E" />
              <span
                id="ai-label-company"
                style={{
                  fontFamily: 'Manrope, sans-serif',
                  fontWeight: 600,
                  fontSize: '11px',
                  textTransform: 'uppercase',
                  color: '#62748E',
                }}
              >
                Company
              </span>
            </div>
            <span
              aria-labelledby="ai-label-company"
              style={{
                fontFamily: 'Manrope, sans-serif',
                fontWeight: 700,
                fontSize: '14px',
                color: '#171727',
              }}
            >
              {startup_name}
            </span>
          </div>

          {/* Divider */}
          <div style={{ height: '1px', background: '#E0E7FF' }} />

          {/* Row 2 — Raising */}
          <div className="flex items-center py-2" style={{ gap: '8px' }}>
            <div className="flex items-center gap-1.5" style={{ minWidth: '80px' }}>
              <TrendingUp size={12} color="#010080" />
              <span
                id="ai-label-raising"
                style={{
                  fontFamily: 'Manrope, sans-serif',
                  fontWeight: 600,
                  fontSize: '11px',
                  textTransform: 'uppercase',
                  color: '#62748E',
                }}
              >
                Raising
              </span>
            </div>
            <span
              aria-labelledby="ai-label-raising"
              style={{
                fontFamily: 'Manrope, sans-serif',
                fontWeight: 700,
                fontSize: '14px',
                color: '#010080',
              }}
            >
              {funding_amount}
            </span>
          </div>

          {/* Divider */}
          <div style={{ height: '1px', background: '#E0E7FF' }} />

          {/* Row 3 — Summary */}
          <div className="flex flex-col pt-2">
            <div className="flex items-center gap-1.5 mb-1">
              <FileText size={12} color="#62748E" />
              <span
                id="ai-label-summary"
                style={{
                  fontFamily: 'Manrope, sans-serif',
                  fontWeight: 600,
                  fontSize: '11px',
                  textTransform: 'uppercase',
                  color: '#62748E',
                }}
              >
                Summary
              </span>
            </div>
            <span
              aria-labelledby="ai-label-summary"
              style={{
                fontFamily: 'Manrope, sans-serif',
                fontWeight: 400,
                fontSize: '13px',
                color: '#45556C',
                lineHeight: '20px',
              }}
            >
              {summaryText}
            </span>
          </div>
        </motion.div>
      )}
    </motion.div>
  );
}

export default AISummaryCard;
